name: my-first-workflow
# scheduler on every push to the repo
on: 
  push:  


jobs:
  job1:
    name: test basic workflow run
    runs-on: ubuntu-latest
    steps:
      - name: running STEP-1
        run: |
          pwd
          ls -ltr
          hostname
      - name: checkout
        uses: actions/checkout@v6.0.3
      - name: step-2
        run: |
          echo `pwd` >> myartifact.txt 
          ls -ltr
          hostname
      - name: upload artifact
        uses:  actions/upload-artifact@v7.0.1
        with:
          name: single_file
          path: ./myartifact.txt

        
