name: my-first-workflow
#trigger on every push on any branch in this repo
on: push

jobs:
  my-first-job:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: |
          pwd
          ls -ltr
          hostname

      - name: step2-checkout
        uses: actions/checkout@v6.0.2
      - name: step-3
        run: |
          pwd
          ls -ltr
          hostname
        
  
