name: my-first-workflow
# scheduler on every push to the repo
on: 
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:     
env:
  ENV_TYPE: DEV
  APP_USER: gawf-tester
  APP_PORT: 80
  
jobs:
  unit-tests:
    name: Running unit tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v7.0.0
      - name: setup python
        uses:  actions/setup-python@v6.2.0
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Unit Tests
        run: pytest -v
      - name: run unit Tests
        run : |
          mkdir reports/
          pytest --junitxml=reports/unit-test-results.xml --cov=. --cov-report=term-missing -v
      - name: uploade code coverage report
        uses: actions/upload-artifact@v7.0.1
        with:
          name: unit-test-report
          path: reports/    
  codeql:
    name: CodeQL Security Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix:
        language: ['python']  
    steps:
      - name: checkout code
        uses: actions/checkout@v7.0.0
      - name: initialize codeql
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "security"
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # Allows SonarQube to verify PR boundaries
      contents: read
    steps:
      - uses: actions/checkout@v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Download Coverage Report
        uses: actions/download-artifact@v7.0.1
        with:
          name: unit-test-report
          path: reports/    
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    name: Build Application
    runs-on: ubuntu-latest
    outputs:
      image_tags: ${{ steps.vars.outputs.IMAGE_TAGS }}
    steps:
      - name: checkout code
        uses: actions/checkout@v7.0.0
      - name: setup Docker buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: generate Image tags
        id: vars
        run: |
          IMAGE_TAGS="${{ github.run_id }}-${GITHUB_SHA::7}"
          echo "IMAGE_TAGS=$IMAGE_TAGS" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: perilious-mav-app:${{ steps.vars.outputs.IMAGE_TAGS }}
          load: true
      - name: Save Docker Image as artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: perilious-mav-app-image
          path: perilious-mav-app.tar     
