name: my-first-workflow
#trigger on every push on any branch in this repo
on: push

jobs:
  my-first-job:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: run single command
        run: echo "hello run the  first github flow"
      - name: check os release
        run: cat /etc/os-release
    
  my-second-job:
    name: job2
    runs-on: ubuntu-latest
    steps:
      - name: checking the host name
        run: hostname
      - name: running multiple commands
        run: | 
          echo "hi welecome to git hub actions"
          echo "current time is `date`"
          sleep 20
  my-third-job:
    name: job3
    needs: my-first-job
    runs-on: ubuntu-latest
    steps:
      - name: job with single dependency
        run: sleep 10
      - name: checking runner info
        shell: pwsh
        run: get-computerinfo
  my-fourth-job:
    name: job4
    needs: [my-first-job,my-second-job,my-third-job]
    runs-on: ubuntu-latest
    steps:
      - name: job for multiple dependencies
        run: sleep 10
      - name: checking runner info
        run: sw_vers
        
  
